spring:
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:myDb;create=true
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect

concurrency:
  pessimisticLocking:
    requiredToSetLockTimeoutForTestsAtStartup: true
    requiredToSetLockTimeoutForEveryQuery: false
    requiredToSetLockTimeoutQueryHint: false
    delayAtTheEndOfTheQueryForPessimisticLockingTestingInMs: 0
    minimalPossibleLockTimeOutInMs: 0
    lockTimeOutInMsForQueryGetItem: 5000
