# Use postgres/example user/password credentials => docker-compose -f db-stack.yml up
version: '3.1'

services:
  db:
    build: .
    image: mysql-test-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql-test-db
    container_name: mysql-test-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
